"""empty message

Revision ID: 13fa718d8848
Revises: 
Create Date: 2020-07-06 11:19:57.834813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "13fa718d8848"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("email", sa.String(length=80), nullable=False),
        sa.Column("password", sa.LargeBinary(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("first_name", sa.String(length=30), nullable=True),
        sa.Column("last_name", sa.String(length=30), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("type", sa.String(length=20), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.Column("amount_paid", sa.Numeric(), nullable=True),
        sa.Column("verified", sa.Boolean(), nullable=True),
        sa.Column("amount_earned", sa.Numeric(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
