"""empty message

Revision ID: 929ba6d7046e
Revises: 3834a12a543e
Create Date: 2020-07-05 18:03:46.192356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "929ba6d7046e"
down_revision = "3834a12a543e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("roles")
    op.add_column("users", sa.Column("type", sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "type")
    op.create_table(
        "roles",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=80), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"],),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###
